Accolate 20 MG Oral Tablet",
Actos 30 MG Oral Tablet",
Atorvastatin Calcium 80 MG Oral Tablet",
Atrovent 18 MCG/ACT AERS (No longer available)",
Axid 150 MG CAPS (No longer available)",
Captopril 25 MG Oral Tablet",
Cardizem CD 120 MG Oral Capsule Extended Release 24 Hour",
Cozaar 25 MG Oral Tablet",
Cozaar 50 MG Oral Tablet",
FLUoxetine HCl - 20 MG Oral Capsule",
Furosemide 40 MG Oral Tablet",
Garlic OIL (No longer available)",
Ginkgo Biloba CAPS (No longer available)",
GlipiZIDE 10 MG Oral Tablet",
GlyBURIDE 5 MG Oral Tablet",
Hydrochlorothiazide 50 MG Oral Tablet",
LORazepam 2 MG Oral Tablet",
Lisinopril 10 MG Oral Tablet",
MetFORMIN HCl - 500 MG Oral Tablet",
Metoprolol Tartrate 100 MG Oral Tablet",
Phenytoin Sodium Extended 100 MG Oral Capsule",
Potassium Chloride 10 MEQ CPCR (No longer available)",
Potassium Chloride ER 10 MEQ Oral Tablet Extended Release",
Propranolol HCl ER 120 MG Oral Capsule Extended Release 24 Hour",