# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40297dd0ea5608c82068950b612244a0e04974d85091fc172a30e4671d77f6094b417e68c3e657c220a3f983859f027044c4573aa87f3b7b7019a52367f40cc9

test:
  secret_key_base: 96d1143b347a9feeb3072f6af847452d7361bd842cfa25c111766b56c67935eed3a80a6417a67b23837810379a748fb47346d7e548de560c6670aa4a58a8a3a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
